
# live reload
live_config_reload = true

# default working directory
working_directory = "None"

# Themes --
# import = [ 
#   "~/.config/alacritty/nordic.toml",
#   "~/.config/alacritty/keybinds.toml"
# ]

[window]
title = "Alacritty"
#decorations = "none"
blur = true
opacity = 0.8
padding.x = 10
padding.y = 10

[window.dimensions]
columns = 160
lines = 80

[cursor.style]
shape= "Beam" # types: Block, Underline, Beam 
blinking = "Never"

[colors]
#transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
#glyph_offset = { x = 1, y = 0 }
normal.family = "JetBrains Mono Nerd Font Mono"
normal.style = "Regular"
size = 16.0

[font.bold]
family = "JetBrains Mono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font Mono"
style = "Italic"
